name: enum_to_string
description: Better conversion of ENUMs to string. Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
version: 1.0.12
homepage: https://github.com/rknell/flutterEnumsToString

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  pedantic: ^1.9.0