name: enum_to_string
description: Better conversion of ENUMs to string. Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
version: 1.0.14
homepage: https://github.com/rknell/flutterEnumsToString

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic:
  test: